#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD vz.cmx ;;
      tests)        $OCAMLBUILD test.native;;
      color_schemes)       shift; jsoo-build $* test/color_schemes.ml ;;
      iris)         shift; jsoo-build $* test/iris.ml ;;
      cam)          shift; jsoo-build $* test/cam.ml ;;
      doc)          shift; pkg-doc $* doc/dev-api.docdir ;;
      clean)        $OCAMLBUILD -clean ;;
      jsoo)         shift; jsoo-build $* ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
